!function () { 'use strict'

const NAME     = 'Oopish Auto'
    , VERSION  = '0.0.1'
    , HOMEPAGE = 'http://auto.oopish.com/'

    , BYLINE   = `\n\n\n\n//\\\\ generated by ${NAME} ${VERSION}\n`
    , HELP =
`
${NAME} ${VERSION}
${'='.repeat( (NAME+VERSION).length+1 )}

This Node.js script generates and edits the class, demo, docs and test files
associated with one or more new class.

Installation
------------
If you haven’t done it already, you should set up the \`ooauto\` alias:
$ node utility/alias.js

Basic Usage
-----------
$ cd /path/to/your/project/     # A project directory in standard Oopish format
$ ooauto --version              # Show the current ${NAME} version
$ ooauto MyClass AnotherClass   # Generate and edit files for the new classes

Generated Files
---------------
1. src/main/MyClass.es6.js                   Source file for the new class
2. src/test/MyClass-universal-test.es6.js    Basic unit tests to start you off
3. src/test/MyClass-browser-test.es6.js      As above, for browsers only
4. src/test/MyClass-nonbrowser-test.es6.js   As above, for Node.js only
5. src/demo/MyClass-demo.es6.js              Usage example script
6. support/demo-myclass.html                 Usage example page (note lowercase)

Edited Files
------------
1. src/main/README.md                        A documentation section
2. support/demos.html                        A link to the list of demos
3. support/test.html                         Two ‘Development ES6’ links
4. support/demo-*.html                       One ‘Development ES6’ link

Options
-------
-h  --help      Show this help message
-v  --version   Show the current ${NAME} version

This script belongs to ${HOMEPAGE}`


//// Validate the environment.
if ( '/utility/auto.js' !== process.argv[1].slice(-16) )
    return console.warn('Unexpected environment!')
if ( ( process.cwd() !== process.argv[1].slice(0,-16) ) )
    return console.warn('Unexpected CWD, try:\n  $ cd /path/to/your/project/')
if ('function' !== typeof require)
    return console.warn('Use Node.js instead:\n  $ node utility/auto.js')




//// SETUP


//// Load library functionality.
const fs = require('fs')

//// Set constants.
const project = process.cwd().split('/').pop()


//// Declare variables.
let opt

//// Deal with command-line options.
while ( opt = process.argv.shift() ) {
    if ('-h' === opt || '--help'    === opt) return console.log(HELP)
    if ('-v' === opt || '--version' === opt) return console.log(VERSION)
}




//// XX
//@todo


}()
