!function () { 'use strict'

const NAME     = 'Oopish Auto'
    , VERSION  = '0.0.3'
    , HOMEPAGE = 'http://auto.oopish.com/'

    , BYLINE   = `\n\n\n\n//\\\\ generated by ${NAME} ${VERSION}\n`
    , HELP =
`
${NAME} ${VERSION}
${'='.repeat( (NAME+VERSION).length+1 )}

This Node.js script generates and edits the class, demo, docs and test files
associated with one or more new class.

Installation
------------
If you haven’t done it already, you should set up the \`ooauto\` alias:
$ node ootility/alias.js

Basic Usage
-----------
$ cd /path/to/your/project/     # A project directory in standard Oopish format
$ ooauto --version              # Show the current ${NAME} version
$ ooauto Foo AnotherClass       # Generate and edit files for the new classes

Generated Files
---------------
1. src/main/Foo.6.js                     Source file for the new class
2. src/test/Foo-universal-test.6.js      Basic unit tests to start you off
3. src/test/Foo-browser-test.6.js        As above, for browsers only
4. src/test/Foo-nonbrowser-test.6.js     As above, for Node.js only
5. src/demo/Foo-demo.6.js                Usage example script
6. support/demo-foo.html                 Usage example page (lowercase foo)

Edited Files
------------
1. src/main/README.md                    A new documentation section
2. support/demos.html                    A link to the new Foo demo
3. support/demo-*.html                   One ‘Development ES6’ link
4. support/docs.html                     A new documentation section
5. support/test.html                     Two ‘Development ES6’ links

Options
-------
-d  --demo      Just create a demo script and page - no class, test or docs
-h  --help      Show this help message
-r  --remove    Remove existing class or classes from the project
-v  --version   Show the current ${NAME} version

This script belongs to ${HOMEPAGE}`


//// Validate the environment.
const nodePath   = process.argv.shift()
const scriptPath = process.argv.shift()
if ( '/ootility/auto.js' !== scriptPath.slice(-17) )
    return console.warn('Unexpected environment!')
if ( ( process.cwd() !== scriptPath.slice(0,-17) ) )
    return console.warn('Unexpected CWD, try:\n  $ cd /path/to/your/project/')
if ('function' !== typeof require)
    return console.warn('Use Node.js instead:\n  $ node ootility/auto.js')




//// SETUP


//// Load library functionality.
const fs = require('fs')

//// Set constants.
const topline = (fs.readFileSync(`src/main/App.6.js`)+'').split('\n')[0]
const projectTC = topline.split(' ')[1]          // titlecase, eg 'FooBar'
const projectLC = process.cwd().split('/').pop() // lowercase, eg 'foobar'
if ( projectLC.toLowerCase() != projectLC) return console.warn(
    `Project '${projectLC}' contains uppercase letters`)
if ( projectTC.toLowerCase() != projectLC) return console.warn(
    `Project '${projectLC}' is called '${projectTC}' in src/main/App.6.js`)

//// Declare variables.
let opt, demo = false, remove = false, classes = []

//// Deal with command-line options.
while ( opt = process.argv.shift() ) {
    if ('-d' === opt || '--demo'    === opt) demo = true
    if ('-h' === opt || '--help'    === opt) return console.log(HELP)
    if ('-r' === opt || '--remove'  === opt) remove = true
    if ('-v' === opt || '--version' === opt) return console.log(VERSION)
    if ( /^[A-Z][A-Za-z0-9]+$/.test(opt) )
        classes.push(opt)
    else
        console.warn(`Ignoring '${opt}' - not a valid option or class-name`)
}

//// Ignore duplicate class-names.
classes = new Set(classes)




//// GENERATE


//// 1. src/main/Foo.6.js                     Source file for the new class

classes.forEach( name => {
    const path = `src/main/${name}.6.js`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateClass(name) )
})


//// 2. src/test/Foo-universal-test.6.js      Basic unit tests to start you off
classes.forEach( name => {
    const path = `src/test/${name}-universal-test.6.js`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateUniversalTest(name) )
})


//// 3. src/test/Foo-browser-test.6.js        As above, for browsers only
classes.forEach( name => {
    const path = `src/test/${name}-browser-test.6.js`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateBrowserTest(name) )
})


//// 4. src/test/Foo-nonbrowser-test.6.js     As above, for Node.js only
classes.forEach( name => {
    const path = `src/test/${name}-nonbrowser-test.6.js`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateNonbrowserTest(name) )
})


//// 5. src/demo/Foo-demo.6.js                Usage example script
classes.forEach( name => {
    const path = `src/demo/${name}-demo.6.js`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateDemoScript(name) )
})


//// 6. support/demo-foo.html                 Usage example page (lowercase foo)
classes.forEach( name => {
    const path = `support/demo-${name.toLowerCase()}.html`
    if ( fs.existsSync(path) ) return console.warn(`${path} already exists`)
    fs.writeFileSync( path, generateDemoPage(name) )
})




//// EDIT


//// 1. src/main/README.md                    A new documentation section
// @todo


//// 2. support/demos.html                    A link to the new Foo demo
// @todo


//// 3. support/demo-*.html                   One ‘Development ES6’ link
// @todo


//// 4. support/docs.html                     A new documentation section
// @todo


//// 5. support/test.html                     Two ‘Development ES6’ links
// @todo







//// UTILITY


////
function generateClass (name) {
    return `${topline}

!function (ROOT) { 'use strict'


ROOT.${projectTC}.${name} = class {

    constructor (config, app) {

        //// Record configuration.
        const defaults = {
            aa:     10
          , bb:     null
          , cc:     app.cc
        }
        Object.assign(this, defaults, config, { app })
    }

    xxx (config) {
        const { app, aa, bb, cc } = this
        const { xx, yy, zz } = config

        ////

    }

}


}( 'object' == typeof global ? global : this ) // \`window\` in a browser
`}


////
function generateUniversalTest (name) {
    const fullName = `${projectTC}.${name}`
    return `${topline}


//// Node.js: 7.2.0
//// Rhino:   [not tested yet]

//// Windows XP: Firefox 6, Chrome 15 (and probably lower), Opera 12.10
//// Windows 7:  IE 9, Safari 5.1
//// OS X 10.6:  Firefox 6, Chrome 16 (and probably lower), Opera 12, Safari 5.1
//// iOS:        iPad 3rd (iOS 6) Safari, iPad Air (iOS 7) Chrome
//// Android:    Xperia Tipo (Android 4), Pixel XL (Android 7.1)




if ('function' != typeof jQuery) throw Error('jQuery not found')
jQuery( function($) { 'use strict'




test('The ${name} class', () => {
    is('function' == typeof ${fullName}   , '\`${fullName}\` is a function')
})




})
`}


////
function generateBrowserTest (name) {
    const fullName = `${projectTC}.${name}`
    return `${topline}


//// Windows XP: Firefox 6, Chrome 15 (and probably lower), Opera 12.10
//// Windows 7:  IE 9, Safari 5.1
//// OS X 10.6:  Firefox 6, Chrome 16 (and probably lower), Opera 12, Safari 5.1
//// iOS:        iPad 3rd (iOS 6) Safari, iPad Air (iOS 7) Chrome
//// Android:    Xperia Tipo (Android 4), Pixel XL (Android 7.1)




if ('function' != typeof jQuery) throw Error('jQuery not found')
jQuery( function($) { 'use strict'




test('The ${name} class', () => {
    is('function' == typeof ${fullName}   , '\`${fullName}\` is a function')
})




})
`}


////
function generateNonbrowserTest (name) {
    const fullName = `${projectTC}.${name}`
    return `${topline}


//// Node.js: 7.2.0
//// Rhino:   [not tested yet]




if ('function' != typeof jQuery) throw Error('jQuery not found')
jQuery( function($) { 'use strict'




test('The ${name} class', () => {
    is('function' == typeof ${fullName}   , '\`${fullName}\` is a function')
})




})
`}


////
function generateDemoScript (name) {
    return `${topline}


if ('function' != typeof jQuery) throw Error('jQuery not found')
jQuery( function($) { 'use strict'


//// Create an instance of ${projectTC} with default configuration.
const ${projectLC} = new ${projectTC}({
})


//// Create an instance of ${name} with default configuration.
const ${name.toLowerCase()} = new ${projectTC}.${name}({
})


})
`}


////
function generateDemoPage (name) {
    const nameLC = name.toLowerCase()
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>${projectTC}.${name} Demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="How to use the ${projectTC}.${name} class">

  <!-- Usage: \`LERT("Some alert message here!")\` -->
  <script>!function(s){var A='addEventListener',L='LERT',S='setAttribute',t=top,
  w=this,d=document,u=navigator.userAgent,n=0,p,i,c,e=function(m,f,l){if(l!=+l)l
  =m.lineno,f=m.filename,m=m.message;for(i=0,c=w;c=c[['LIFE','pop','is','ready']
  [i++]];);(4<i&&w.LIFE.pop.warn||t[L])((f+':'+l).match(/[^\\/]+?\\/?[^\\/]+$/)[0]+
  '\\n'+m)};/efox\\/(\\d|[1-2]\\d)\\.|Prest/.test(u)?w.onerror=e:!/SIE 9/.test(u)&&w[
  A]?w[A]('error',e,0):w.attachEvent('onerror',e);w[L]=t[L]=t[L]||function(h){h=
  98<++n?'99!':n+' '+h;99<n?0:d.body?(p=d.createElement('TT'),p.innerHTML=h,(p.
  style[S]?p.style[S]('cssText',s):p[S]('style',s)),p.onclick=function(){d.body.
  removeChild(this)},d.body.appendChild(p)):alert(h)}}('position:fixed!importa'+
  'nt;position:absolute;display:block;top:40%;left:5%;width:90%;font-size:14px'+
  ';padding:9px;margin-left:-9px;background:tan;color:#603;z-index:99')</script>

</head>
<body style="font-family:Arial, sans-serif; background:#ccc; color:#333">

  <!-- Dropdown menu to select JavaScript format -->
  <select id="es" style="float:right" onchange="document.cookie='es='
    +this.options[this.selectedIndex].value;location.reload()">
    <option value="~0~">Production ES5</option><!-- default -->
    <option value="~1~">Production Minified ES5</option>
    <option value="~2~">Production ES6</option>
    <option value="~3~">Development ES6</option>
  </select>
  <script>!function(d,i,s){i=~~d.cookie.split('~')[1];s=d.getElementById('es')
  if(s)s.options[i].selected=true}(document)</script>

  <!-- Header and Navigation menu -->
  <h1 style="display:inline">${projectTC} <span id="version">0.0.*</span></h1>

  <a href="../index.html">Home</a> &nbsp;
  <a href="test.html">Test</a> &nbsp;
  <a href="demos.html">Demos</a> &nbsp;
  <a href="https://github.com/@todo">GitHub</a> &nbsp;

  <h2 style="margin-top:0.2em">${projectTC}.${name} Demo</h2>

  <!-- Upgrade message for Internet Explorer 8 and below -->
  <!--[if lte IE 8]>
  <h2>Please upgrade to Internet Explorer 9 or higher</h2>
  <script>document.getElementById('version').innerHTML='Not Supported'</script>
  <![endif]-->

  <!--[if gte IE 9 | !IE ]><!--><!-- Begin hiding from IE 8 and below -->

  <!-- Displays the demo -->
  <pre id="dump" style="font: 18px Monaco,'Lucida Console',monospace;
    background:#cde; width:48em; line-height:1.15"></pre>

  <!-- Load the proper scripts, according to the <SELECT> dropdown menu -->
  <script>!function (d) { 'use strict'
      var i = ~~d.cookie.split('~')[1] // 0 - 3
        , f = (3 == i) ? '../src/' : '../dist/' // folder
        , s = // src values
              (1 == i) ? [ // Production Minified ES5
                , '../lib/traceur-runtime.min.js'
                , f + 'main/${projectLC}.5.min.js'
                , f + 'demo/${nameLC}-demo.5.js' // no need to minify
              ]
            : (2 == i) ? [ // Production ES6
                  f + 'main/${projectLC}.6.js'
                , f + 'demo/${nameLC}-demo.6.js'
              ]
            : (3 == i) ? [ // Development ES6
                  f + 'main/App.6.js'
                , f + 'main/@todo.6.js'
                , f + 'main/@todo.6.js'
                , f + 'main/@todo.6.js'
                , f + 'main/${name}.6.js'
                , f + 'demo/${name}-demo.6.js'
              ]
            : [ // Production ES5 (the default, if no cookie has been set)
                , '../lib/traceur-runtime.js'
                , f + 'main/${projectLC}.5.js'
                , f + 'demo/${nameLC}-demo.5.js'
              ]
        , B = '<script src="'  // begin
        , E = '"></'+'script>' // end
      s.unshift('../lib/jquery-3.1.1.min.js') // start with jQuery
      d.write(B + s.join(E + B) + E)
  }(document)</script>

  <!-- Display the version -->
  <script>$('#version').html(${projectTC}.VERSION||'VERSION not found')</script>

  <!--<![endif]--><!-- End hiding from Internet Explorer 8 and below -->

</body>
</html>
`}



}()
